services:
  seq-input-syslog:
    image: datalust/seq-input-syslog:latest
    depends_on:
      - seq
    ports:
      - "514:514/udp"
    environment:
      - SEQ_ADDRESS=http://seq:5341
      - BASE_URI=http://127.0.0.1:5341
      - SEQ_API_CANONICALURI=http://127.0.0.1:5341
      - TZ="Europe/Paris"
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=http://127.0.0.1:5341
      - SEQ_API_CANONICALURI=http://127.0.0.1:5341
      - TZ="Europe/Paris"
    restart: unless-stopped
    volumes:
      - ./seq-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
